In [ ]:
# .head()
# .info()
# df.loc[df.duplicated()]
# df.loc[df["primary_key"].isna()]
# pd.to_datetime(df["date"])

In [2]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("sheelakasbekar/books-data-set")

print("Path to dataset files:", path)

Downloading to C:\Users\chiar\.cache\kagglehub\datasets\sheelakasbekar\books-data-set\1.archive...

100%|██████████| 34.9k/34.9k [00:00<00:00, 1.77MB/s]

Extracting files...
Path to dataset files: C:\Users\chiar\.cache\kagglehub\datasets\sheelakasbekar\books-data-set\versions\1

In [3]:
import os
os.listdir(path)

['Books.csv', 'Customers.csv', 'Orders.csv']

In [4]:
import pandas as pd
file1 = os.path.join(path, 'Books.csv')
books = pd.read_csv(file1)
books.head()

,Book_ID,Title,Author,Genre,Published_Year,Price,Stock
0,1,Configurable modular throughput,Joseph Crane,Biography,1949,21.34,100
1,2,Persevering reciprocal knowledge user,Mario Moore,Fantasy,1971,35.80,19
2,3,Streamlined coherent initiative,Derrick Howard,Non-Fiction,1913,15.75,27
3,4,Customizable 24hour product,Christopher Andrews,Fiction,2020,43.52,8
4,5,Adaptive 5thgeneration encoding,Juan Miller,Fantasy,1956,10.95,16

In [5]:
books.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Book_ID         500 non-null    int64
 1   Title           500 non-null    object
 2   Author          500 non-null    object
 3   Genre           500 non-null    object
 4   Published_Year  500 non-null    int64
 5   Price           500 non-null    float64
 6   Stock           500 non-null    int64
dtypes: float64(1), int64(3), object(3)
memory usage: 27.5+ KB

In [6]:
books.loc[books.duplicated()]

Empty DataFrame
Columns: [Book_ID, Title, Author, Genre, Published_Year, Price, Stock]
Index: []

In [7]:
books.loc[books["Book_ID"].isna()]

Empty DataFrame
Columns: [Book_ID, Title, Author, Genre, Published_Year, Price, Stock]
Index: []

In [8]:
file2 = os.path.join(path, 'Customers.csv')
customers = pd.read_csv(file2)
customers.head()

,Customer_ID,Name,Email,Phone,City,Country
0,1,Deborah Griffith,balljoseph@wright-keith.net,1234567891,South Craigfort,Denmark
1,2,Crystal Clements,kimberlybennett@curtis.com,1234567892,East Derekberg,Nicaragua
2,3,Susan Fuller,beanmichael@burnett-stewart.net,1234567893,Austinbury,Equatorial Guinea
3,4,Jamie Ramirez,amandahood@warren.com,1234567894,Dianamouth,Slovenia
4,5,Marcus Murphy,connerjohn@yahoo.com,1234567895,Smithbury,Guinea-Bissau

In [9]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Customer_ID  500 non-null    int64
 1   Name         500 non-null    object
 2   Email        500 non-null    object
 3   Phone        500 non-null    int64
 4   City         500 non-null    object
 5   Country      500 non-null    object
dtypes: int64(2), object(4)
memory usage: 23.6+ KB

In [10]:
customers.loc[customers.duplicated()]

Empty DataFrame
Columns: [Customer_ID, Name, Email, Phone, City, Country]
Index: []

In [11]:
customers.loc[customers["Customer_ID"].isna()]

Empty DataFrame
Columns: [Customer_ID, Name, Email, Phone, City, Country]
Index: []

In [12]:
file3 = os.path.join(path, 'Orders.csv')
orders = pd.read_csv(file3)
orders.head()

   Order_ID  Customer_ID  Book_ID  Order_Date  Quantity  Total_Amount
0         1           84      169  2023-05-26         8        188.56
1         2          137      301  2023-01-23        10        216.60
2         3          216      261  2024-05-27         6         85.50
3         4          433      343  2023-11-25         7        301.21
4         5           14      431  2023-07-26         7        136.36

In [13]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Order_ID      500 non-null    int64
 1   Customer_ID   500 non-null    int64
 2   Book_ID       500 non-null    int64
 3   Order_Date    500 non-null    object
 4   Quantity      500 non-null    int64
 5   Total_Amount  500 non-null    float64
dtypes: float64(1), int64(4), object(1)
memory usage: 23.6+ KB

In [14]:
orders.loc[orders.duplicated()]

Empty DataFrame
Columns: [Order_ID, Customer_ID, Book_ID, Order_Date, Quantity, Total_Amount]
Index: []

In [15]:
orders.loc[orders["Order_ID"].isna()]

Empty DataFrame
Columns: [Order_ID, Customer_ID, Book_ID, Order_Date, Quantity, Total_Amount]
Index: []

In [25]:
orders["Order_Date"] = pd.to_datetime(orders["Order_Date"])
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Order_ID      500 non-null    int64
 1   Customer_ID   500 non-null    int64
 2   Book_ID       500 non-null    int64
 3   Order_Date    500 non-null    datetime64[ns]
 4   Quantity      500 non-null    int64
 5   Total_Amount  500 non-null    float64
dtypes: datetime64[ns](1), float64(1), int64(4)
memory usage: 23.6 KB

In [27]:
books.to_csv("books_pulita.csv", index=False)
customers.to_csv("customers_pulita.csv", index=False)
orders.to_csv("orders_pulita.csv", index=False)